[package]
name = "larsen-dev/signal"
description = "User-written RBXScriptSignal based on known GoodSignal and Signal+ practices. Fast, reliable and performance-friendly."
keywords = ["generic", "typed", "event", "fast", "signal", "performance", "optimization", "efficient"]
version = "1.0.0"
license = "MIT"
authors = ["Larsen-dev"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/Larsen-dev/signal"

exclude = [
    ".github",
    ".gitignore",
    "README.md",
    "aftman.toml",
    "selene.toml",
    "roblox.yml",
    "default.project.json",
    "*.spec.luau"
]

[dependencies]
