[package]
name = "larsen-dev/collections"
description = "Simple collections module."
keywords = ["generic", "typed", "fast", "performance", "efficient"]
version = "0.1.1"
license = "MIT"
authors = ["Larsen-dev"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/Larsen-dev/collections"

exclude = [
    ".github",
    ".gitignore",
    "README.md",
    "aftman.toml",
    "selene.toml",
    "roblox.yml",
    "default.project.json",
    "*.spec.luau"
]

[dependencies]
